config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#home'
end

app/models/admin_user.rb
class AdminUser < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: {submitted: 0, approved: 1, rejected: 2}
  belongs_to :user
  validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates_presence_of :first_name, :last_name

  def full_name
    last_name.capitalize + ", " + first_name.capitalize
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin

  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Your post was edited successfully"
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: "Your post was deleted successfully"
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:date, :rationale, :status)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
		"active" if current_page?(path)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OvertimeManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" rel="stylesheet' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div class="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div class="alert_wrapper">
        <p class="notice"><%= alert %></p>
      </div>
    <% end %>

    <%= render 'shared/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<section class="container-fluid general-form-container">
  <% if post.errors.any? %>
    <div id="error_explanation" class="validate-errors-alert">
      <!-- <h2 class="h2-styles h2-errors"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2> -->
      <% post.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <section class="post-form-container col-md-4 col-md-offset-4">
    <h1 class="h1-styles">Create New Overtime Request</h1>
    <%= form_with(model: post, local: true, class: 'general-form-styles') do |form| %>

      <div class="form-group">
        <%= form.label :date %>
        <%= form.date_field :date, id: :post_date, class: 'form-control custom-input-text-general' %>
      </div>

      <div class="form-group">
        <%= form.label :rationale %>
        <%= form.text_area :rationale, id: :post_rationale, class: 'form-control custom-input-text-general' %>
      </div>

      <%= render partial: 'status', locals: { form: form } if current_user.type == 'AdminUser' %>

      <div class="form-group">
        <%= form.submit "Save", class: 'btn btn-primary login-button' %>
      </div>
    <% end %>
  </section>
</section>

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id %>
	</td>
	<td>
		<%= post.date %>
	</td>
	<td>
		<%= post.user.full_name %>
	</td>
	<td>
		<%= truncate(post.rationale) %>
	</td>
	<td>
		<%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}" %>
	</td>
	<td>
		<%= link_to 'Delete', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", data: { confirm: 'Are you sure?' } %>
	</td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= form.label :status, 'Submitted' %>
  <%= form.radio_button :status, 'submitted', id: 'post_status_submitted' %>

  <%= form.label :status, 'Approved' %>
  <%= form.radio_button :status, 'approved', id: 'post_status_approved' %>

  <%= form.label :status, 'Rejected' %>
  <%= form.radio_button :status, 'rejected', id: 'post_status_rejected' %>
</div>

app/views/posts/edit.html.erb
<!-- <h2 class="h2-styles">Edit</h2> -->

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<section class="container">
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>
					#
				</th>
				<th>
					Date
				</th>
				<th>
					User
				</th>
				<th>
					Rationale
				</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%= render @posts %>
		</tbody>
	</table>
</section>

app/views/posts/new.html.erb
<!-- <h1 class="h1-styles">New</h1> -->

<%= render 'form', post: @post %>

<!-- <%= link_to 'Back', posts_path %> -->

app/views/posts/show.html.erb
<h2><%= @post.inspect %></h2>

app/views/shared/_navigation.html.erb
<section class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">Time Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
  			<li class="<%= active?(posts_path) %>">
  				<%= link_to "Time Entries", posts_path, class: 'nav-link' %>
        </li>
  			<li class="<%= active?(new_post_path) %>">
  				<%= link_to "Add New Entry", new_post_path, id: 'new_post_from_nav', class: 'nav-link' %>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if current_user.type == 'AdminUser' %>
              <%= link_to "Admin Dashboard", admin_root_path %>
              <div class="dropdown-divider"></div>
            <% end %>

            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </div>
        </li>
      </ul>

    </div>
  </nav>

</section>